### ISSUE TITLE
Markdown file missing

### ISSUE THREAD

**Issue by gowrishankarin** [LegsTech007/RepData_PeerAssignment1#1]
Hi...

I am evaluating your code for coursera course now... unable to find the md file. Would you please check-in asap. I can see you have done the work but Rmd and html files are not sufficient to complete my task.

Regards

**Comment by LegsTech007** [comment]
Ok its added but the commit no longer matches.  I appreciate the heads up.

**Comment by gowrishankarin** [comment]
Now u did not add the images... pics are missing, waiting for your update.

**Comment by LegsTech007** [comment]
Updated

**Comment by gowrishankarin** [comment]
Cool... Job Done!!

**Comment by BhishmaRao** [comment]
Hi
please check once and evaluate
